development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_development
  pool: 5
  username: mercator
  password: humunculus

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_test
  pool: 5
  username: mercator
  password: humunculus

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_production
  pool: 5
  username: mercator
  password: humunculus