development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_development
  pool: 5
  username: <%= CONFIG[:development_database_user] %>
  password: <%= CONFIG[:development_database_password] %>

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_test
  pool: 5
  username: <%= CONFIG[:test_database_user] %>
  password: <%= CONFIG[:test_database_password] %>

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_production
  pool: 5
  username: <%= CONFIG[:production_database_user] %>
  password: <%= CONFIG[:production_database_password] %>

import_development:
  adapter: mysql2
  host: localhost
  database: ivellio_vellin_development
  username: <%= CONFIG[:legacy_database_user] %>
  password: <%= CONFIG[:legacy_database_password] %>