### Rails ###

development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercator_development
  pool: 5
  username: <%= CONFIG[:development_database_user] %>
  password: <%= CONFIG[:development_database_password] %>

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercator_test
  pool: 5
  username: <%= CONFIG[:test_database_user] %>
  password: <%= CONFIG[:test_database_password] %>

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercator_production
  pool: 5
  username: <%= CONFIG[:production_database_user] %>
  password: <%= CONFIG[:production_database_password] %>

demo:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercator_production
  pool: 5
  username: <%= CONFIG[:production_database_user] %>
  password: <%= CONFIG[:production_database_password] %>

### Lecgacy (Opensteam) ###

import_development:
  adapter: mysql2
  host: localhost
  database: ivellio_vellin_development
  username: <%= CONFIG[:legacy_database_user] %>
  password: <%= CONFIG[:legacy_database_password] %>

import_production:
  adapter: mysql2
  host: localhost
  database: ivellio_vellin_production
  username: <%= CONFIG[:legacy_database_user] %>
  password: <%= CONFIG[:legacy_database_password] %>

### Mesonic  ###

mesonic_cwldaten_development:
  adapter: sqlserver
  host: <%= CONFIG[:erp_host] %>
  port: <%= CONFIG[:erp_database_port] %>
  instance: <%= CONFIG[:erp_database_instance] %>
  database: <%= CONFIG[:erp_database_name] %>
  username: <%= CONFIG[:erp_database_user] %>
  password: <%= CONFIG[:erp_database_password] %>
  encoding: utf8
  timeout: 5000

### Bechlem ###

bechlem:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: bechlem
  pool: 5
  username: <%= CONFIG[:development_database_user] %>
  password: <%= CONFIG[:development_database_password] %>