development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_development
  pool: 5
  username: <%= CONFIG[:development_database_user] %>
  password: <%= CONFIG[:development_database_password] %>

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_test
  pool: 5
  username: mercator
  password: humunculus

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mercator_production
  pool: 5
  username: mercator
  password: humunculus

import_development:
  adapter: mysql2
  host: localhost
  database: ivellio_vellin_development
  username: iv
  password: iv123°§ℓ