### Rails ###

staging:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: mercator_staging
  pool: 5
  username: <%= CONFIG[:staging_database_user] %>
  password: <%= CONFIG[:staging_database_password] %>

### Lecgacy (Opensteam) ###

legacy_import:
  adapter: mysql2
  host: localhost
  database: ivellio_vellin_development
  username: <%= CONFIG[:legacy_database_user] %>
  password: <%= CONFIG[:legacy_database_password] %>

### Mesonic  ###

mesonic_cwldaten:
  adapter: sqlserver
  host: <%= CONFIG[:erp_host] %>
  port: <%= CONFIG[:erp_database_port] %>
  instance: <%= CONFIG[:erp_database_instance] %>
  database: <%= CONFIG[:erp_database_name] %>
  username: <%= CONFIG[:erp_database_user] %>
  password: <%= CONFIG[:erp_database_password] %>
  encoding: utf8
  timeout: 5000

### Bechlem ###

bechlem:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: bechlem
  pool: 5
  username: <%= CONFIG[:staging_database_user] %>
  password: <%= CONFIG[:staging_database_password] %>
