# translations:
#   - file: "app/assets/javascripts/i18n/translations.js"
#     only: "*"
#
translations:
  - file: 'app/assets/javascripts/i18n/cm.js'
    only: [ '*.js.cm', '*.attributes', '*.mercator.states']

  - file: 'app/assets/javascripts/i18n/pm.js'
    only: [ '*.js.pm', '*.attributes', '*.mercator.states']

  - file: 'app/assets/javascripts/i18n/con.js'
    only: [ '*.js.con', '*.attributes', '*.mercator.states']