development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://www.informatom.com/faye"
  secret_token: "b90bf8ef08ea1ed350a49d74fa002602e0fd8ad5364ba9b04a0316d7a632839b"
  signature_expiration: 3600 # one hour
