development:
  server: "http://www.informatom.com:9292/faye/faye"
  secret_token: "<%= CONFIG[:faye_secret_token] %>"
test:
  server: "http://www.informatom.com:9292/faye/faye"
  secret_token: "<%= CONFIG[:faye_secret_token] %>"
production:
  server: "http://www.informatom.com:9292/faye/faye"
  secret_token: "<%= CONFIG[:faye_secret_token] %>"
  signature_expiration: 3600 # one hour
